language: rust
cache: cargo

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - name="roomservice-rust-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/roomservice-rust $name/
    - cp LICENSE $name/
    - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    api_key:
      secure: RZ73VGkvajT+2pGalBZUT5R806hmI0cNkFPYgEwQfU8FFqYCBnCRK0SZDILlyhGlPPzC/pgHVQvfLc1Krg2JCQaS2zzrn1Y9LYsyteH7RNrUmbocTqutOiCZRAegaKj04a6nbofFcWdLOybnMa8K1eHtTOE3lMNXaQcRjjUcXY/NOVdxUTAbcPnS0ZRnXuXSK5uAgcEj37v755brLJz392NepBo36yzIx23um5MCOVGum1MHfhwcJ9VIALHk9oAHfwJuSguIU+9TBAA0MDexGAt9NtlWsXJWRwnsX0i1Dvg4XhIYLK9mX0DPpjdlDoaKzAVwqteBQgoq/+3Ak0dQr3sB50QnUBnXEoJLP0/j3NFkQhaxap9fKC9PK3OR97j/ijzOV/Cu3bop7vQonIhHnfjN/mv1d/3JXPAYJNbIZLxNuYlOb8SEQ2oFCLqHtGPN6rxPdBfFg87NTc2FIFTorsbP3OI1epHWbWrDsoFeLRT/VubWn5mvHEakWNNDY5ttPT5EJsPfUc+1oDdB50smyMmqhb+WJS6y6Rv4NGCiAnvQzKxTfqOtFpJIBwTOpXZtWBHuxQsNwjLRt9/XeVukRI2PchMIHAHo+A5zHwnFhybpSSBtafm+NvOXRNP+6AjIcFiT+/CEDIC8CbhQka1HG7qypBeMX4HlvuZNEfBKj2U=
    file: roomservice-rust-$TRAVIS_TAG-$TARGET.tar.gz
    on:
      repo: curtiswilkinson/roomservice-rust

matrix:
  include:

  - name: Tests
    env: RUST_BACKTRACE=1
    rust: nightly
    script:
    - cargo test --locked

  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: nightly
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET --locked 
    addons:
      apt:
        packages:
          - musl-tools
    <<: *DEPLOY_TO_GITHUB

  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
    script: cargo build --release --target $TARGET --locked
    install: true
    <<: *DEPLOY_TO_GITHUB
