beforeAll: echo beforeAll
rooms:
  room_one:
    path: ./src/
    beforeSynchronous: sleep 4
    before: sleep 2
    after: echo "hi"
  room_two:
    path: ./src/
    beforeSynchronous: sleep 5
    before: echo hi
afterAll: echo afterAll
