beforeAll: echo beforeAll
rooms:
  room_one:
    path: ./src/
    before: sleep 5
    runSynchronous: sleep 3
    after: echo "hi"
  room_two:
    path: ./src/
    before: sleep 3
    runSynchronous: sleep 3
afterAll: echo afterAll
